In [22]:
import numpy
X = numpy.loadtxt("./data/Train/X_train.txt")
y = numpy.loadtxt("./data/Train/y_train.txt")

In [27]:
from models import adaboost
my_model = adaboost.without_penalty(X[:100], y[:100])

/home/mahdi/.local/share/virtualenvs/machine-learning-final-project-uk2p9d2v/lib/python3.6/site-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


/home/mahdi/.local/share/virtualenvs/machine-learning-final-project-uk2p9d2v/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
/home/mahdi/.local/share/virtualenvs/machine-learning-final-project-uk2p9d2v/lib/python3.6/site-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


[0.33333333 0.47619048 0.45       0.38888889 0.47058824]
0.4238001867413632


sklearn.ensemble.weight_boosting.AdaBoostClassifier

array([[2., 2.],
       [0., 0.]])

array([2, 0])