In [1]:
import numpy
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from src import preprocessing
X = numpy.loadtxt("./data/Train/X_train.txt")
y = numpy.loadtxt("./data/Train/y_train.txt")

In [6]:
X, y = shuffle(X, y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10)
size_training = len(X_train)

In [12]:
from models import adaboost
from sklearn.metrics import accuracy_score
ks = [.5, .10, .20, .50, 1]
report = []
for k in ks:
    adaboost_model = adaboost.without_penalty(X_train[:int(k*size_training)], y_train[:int(k*size_training)])
    y_pred = adaboost_model.predict(X_test)
    score = accuracy_score(y_test, y_pred)
    data={
        'k': k,
        'score': score
    }
    report.append(data)

/home/mahdi/.local/share/virtualenvs/machine-learning-final-project-uk2p9d2v/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


[0.42532006 0.59629101 0.45857143 0.5251076  0.45677233]
0.4924124873240799


/home/mahdi/.local/share/virtualenvs/machine-learning-final-project-uk2p9d2v/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


/home/mahdi/.local/share/virtualenvs/machine-learning-final-project-uk2p9d2v/lib/python3.6/site-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 4 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


[0.57241379 0.66197183 0.53956835 0.38405797 0.4962963 ]
0.5308616473447788


/home/mahdi/.local/share/virtualenvs/machine-learning-final-project-uk2p9d2v/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


[0.41197183 0.5141844  0.61648746 0.5234657  0.51811594]
0.5168450658692547


/home/mahdi/.local/share/virtualenvs/machine-learning-final-project-uk2p9d2v/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


[0.41820768 0.47360913 0.59571429 0.40602582 0.6167147 ]
0.5020543238529769


[0.64861012 0.49071429 0.44571429 0.5218638  0.37715517]
0.4968115328588884


In [13]:
report

[{'k': 0.5, 'score': 0.46332046332046334},
 {'k': 0.1, 'score': 0.5418275418275418},
 {'k': 0.2, 'score': 0.5598455598455598},
 {'k': 0.5, 'score': 0.5701415701415702},
 {'k': 1, 'score': 0.5186615186615187}]